version: 2

updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    schedule:
      interval: monthly
    directories:
      - /
      - /concision
      - /core
      - /data
      - /derive
      - /ext
      - /init
      - /macros
      - /params
      - /traits
