name: cargo-publish

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

on:
  repository_dispatch:
    types: [crates-io, cargo-publish]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  crates-io:
    environment: crates-io
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - concision-traits
          - concision-init
          - concision-params
          - concision-core
          - concision-data
          - concision-derive
          - concision-macros
          - concision
          - concision-ext
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ github.event.client_payload.ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Publish (${{ matrix.package }})
        run: cargo publish --locked --package ${{ matrix.package }}
