name: Publish

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  repository_dispatch:
    types: [ deploy, publish, cargo-publish, crates-io ]
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish the crate(s) to crates.io?'
        type: boolean

jobs:
  crates-io:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
    environment:
      name: crates-io
    outputs:
      url:  ${{ steps.results.outputs.url }}
    permissions:
      contents: read
      deployments: write
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - concision-init
          - concision-utils
          - concision-core
          - concision-data
          - concision-neural
          - concision-derive
          - concision-macros
          - concision
          - concision-ext
          # non-sdk packages
          - concision-kan
          - concision-s4
          - concision-transformer
          - concision-models
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Publish (${{ matrix.package }})
        id: publish
        run: cargo publish --locked --package ${{ matrix.package }}
      -
        name: Set output(s)
        id: results
        run:
          echo "url=https://crates.io/crates/${{ matrix.package }}" >> "$GITHUB_OUTPUT"
